<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260710062323 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'MediaRelation: CropSizes embeddable (+laptop), migration donnees max*.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE upa_core_configuration_media_relations ADD cropWidthDesktop INT DEFAULT NULL, ADD cropHeightDesktop INT DEFAULT NULL, ADD cropWidthLaptop INT DEFAULT NULL, ADD cropHeightLaptop INT DEFAULT NULL, ADD cropWidthTablet INT DEFAULT NULL, ADD cropHeightTablet INT DEFAULT NULL, ADD cropWidthMobile INT DEFAULT NULL, ADD cropHeightMobile INT DEFAULT NULL');
        $this->addSql('ALTER TABLE upa_gdpr_group_media_relations ADD cropWidthDesktop INT DEFAULT NULL, ADD cropHeightDesktop INT DEFAULT NULL, ADD cropWidthLaptop INT DEFAULT NULL, ADD cropHeightLaptop INT DEFAULT NULL, ADD cropWidthTablet INT DEFAULT NULL, ADD cropHeightTablet INT DEFAULT NULL, ADD cropWidthMobile INT DEFAULT NULL, ADD cropHeightMobile INT DEFAULT NULL');
        $this->addSql('ALTER TABLE upa_layout_block_media_relations ADD cropWidthDesktop INT DEFAULT NULL, ADD cropHeightDesktop INT DEFAULT NULL, ADD cropWidthLaptop INT DEFAULT NULL, ADD cropHeightLaptop INT DEFAULT NULL, ADD cropWidthTablet INT DEFAULT NULL, ADD cropHeightTablet INT DEFAULT NULL, ADD cropWidthMobile INT DEFAULT NULL, ADD cropHeightMobile INT DEFAULT NULL');
        $this->addSql('ALTER TABLE upa_layout_page_media_relations ADD cropWidthDesktop INT DEFAULT NULL, ADD cropHeightDesktop INT DEFAULT NULL, ADD cropWidthLaptop INT DEFAULT NULL, ADD cropHeightLaptop INT DEFAULT NULL, ADD cropWidthTablet INT DEFAULT NULL, ADD cropHeightTablet INT DEFAULT NULL, ADD cropWidthMobile INT DEFAULT NULL, ADD cropHeightMobile INT DEFAULT NULL');
        $this->addSql('ALTER TABLE upa_layout_zone_media_relations ADD cropWidthDesktop INT DEFAULT NULL, ADD cropHeightDesktop INT DEFAULT NULL, ADD cropWidthLaptop INT DEFAULT NULL, ADD cropHeightLaptop INT DEFAULT NULL, ADD cropWidthTablet INT DEFAULT NULL, ADD cropHeightTablet INT DEFAULT NULL, ADD cropWidthMobile INT DEFAULT NULL, ADD cropHeightMobile INT DEFAULT NULL');
        $this->addSql('ALTER TABLE upa_media_relation ADD cropWidthDesktop INT DEFAULT NULL, ADD cropHeightDesktop INT DEFAULT NULL, ADD cropWidthLaptop INT DEFAULT NULL, ADD cropHeightLaptop INT DEFAULT NULL, ADD cropWidthTablet INT DEFAULT NULL, ADD cropHeightTablet INT DEFAULT NULL, ADD cropWidthMobile INT DEFAULT NULL, ADD cropHeightMobile INT DEFAULT NULL');
        $this->addSql('ALTER TABLE upa_module_agenda_media_relations ADD cropWidthDesktop INT DEFAULT NULL, ADD cropHeightDesktop INT DEFAULT NULL, ADD cropWidthLaptop INT DEFAULT NULL, ADD cropHeightLaptop INT DEFAULT NULL, ADD cropWidthTablet INT DEFAULT NULL, ADD cropHeightTablet INT DEFAULT NULL, ADD cropWidthMobile INT DEFAULT NULL, ADD cropHeightMobile INT DEFAULT NULL');
        $this->addSql('ALTER TABLE upa_module_catalog_category_media_relations ADD cropWidthDesktop INT DEFAULT NULL, ADD cropHeightDesktop INT DEFAULT NULL, ADD cropWidthLaptop INT DEFAULT NULL, ADD cropHeightLaptop INT DEFAULT NULL, ADD cropWidthTablet INT DEFAULT NULL, ADD cropHeightTablet INT DEFAULT NULL, ADD cropWidthMobile INT DEFAULT NULL, ADD cropHeightMobile INT DEFAULT NULL');
        $this->addSql('ALTER TABLE upa_module_catalog_feature_media_relations ADD cropWidthDesktop INT DEFAULT NULL, ADD cropHeightDesktop INT DEFAULT NULL, ADD cropWidthLaptop INT DEFAULT NULL, ADD cropHeightLaptop INT DEFAULT NULL, ADD cropWidthTablet INT DEFAULT NULL, ADD cropHeightTablet INT DEFAULT NULL, ADD cropWidthMobile INT DEFAULT NULL, ADD cropHeightMobile INT DEFAULT NULL');
        $this->addSql('ALTER TABLE upa_module_catalog_feature_value_media_relations ADD cropWidthDesktop INT DEFAULT NULL, ADD cropHeightDesktop INT DEFAULT NULL, ADD cropWidthLaptop INT DEFAULT NULL, ADD cropHeightLaptop INT DEFAULT NULL, ADD cropWidthTablet INT DEFAULT NULL, ADD cropHeightTablet INT DEFAULT NULL, ADD cropWidthMobile INT DEFAULT NULL, ADD cropHeightMobile INT DEFAULT NULL');
        $this->addSql('ALTER TABLE upa_module_catalog_media_relations ADD cropWidthDesktop INT DEFAULT NULL, ADD cropHeightDesktop INT DEFAULT NULL, ADD cropWidthLaptop INT DEFAULT NULL, ADD cropHeightLaptop INT DEFAULT NULL, ADD cropWidthTablet INT DEFAULT NULL, ADD cropHeightTablet INT DEFAULT NULL, ADD cropWidthMobile INT DEFAULT NULL, ADD cropHeightMobile INT DEFAULT NULL');
        $this->addSql('ALTER TABLE upa_module_catalog_product_lot_media_relations ADD cropWidthDesktop INT DEFAULT NULL, ADD cropHeightDesktop INT DEFAULT NULL, ADD cropWidthLaptop INT DEFAULT NULL, ADD cropHeightLaptop INT DEFAULT NULL, ADD cropWidthTablet INT DEFAULT NULL, ADD cropHeightTablet INT DEFAULT NULL, ADD cropWidthMobile INT DEFAULT NULL, ADD cropHeightMobile INT DEFAULT NULL');
        $this->addSql('ALTER TABLE upa_module_catalog_product_media_relations ADD cropWidthDesktop INT DEFAULT NULL, ADD cropHeightDesktop INT DEFAULT NULL, ADD cropWidthLaptop INT DEFAULT NULL, ADD cropHeightLaptop INT DEFAULT NULL, ADD cropWidthTablet INT DEFAULT NULL, ADD cropHeightTablet INT DEFAULT NULL, ADD cropWidthMobile INT DEFAULT NULL, ADD cropHeightMobile INT DEFAULT NULL');
        $this->addSql('ALTER TABLE upa_module_catalog_sub_category_media_relations ADD cropWidthDesktop INT DEFAULT NULL, ADD cropHeightDesktop INT DEFAULT NULL, ADD cropWidthLaptop INT DEFAULT NULL, ADD cropHeightLaptop INT DEFAULT NULL, ADD cropWidthTablet INT DEFAULT NULL, ADD cropHeightTablet INT DEFAULT NULL, ADD cropWidthMobile INT DEFAULT NULL, ADD cropHeightMobile INT DEFAULT NULL');
        $this->addSql('ALTER TABLE upa_module_faq_media_relations ADD cropWidthDesktop INT DEFAULT NULL, ADD cropHeightDesktop INT DEFAULT NULL, ADD cropWidthLaptop INT DEFAULT NULL, ADD cropHeightLaptop INT DEFAULT NULL, ADD cropWidthTablet INT DEFAULT NULL, ADD cropHeightTablet INT DEFAULT NULL, ADD cropWidthMobile INT DEFAULT NULL, ADD cropHeightMobile INT DEFAULT NULL');
        $this->addSql('ALTER TABLE upa_module_faq_question_media_relations ADD cropWidthDesktop INT DEFAULT NULL, ADD cropHeightDesktop INT DEFAULT NULL, ADD cropWidthLaptop INT DEFAULT NULL, ADD cropHeightLaptop INT DEFAULT NULL, ADD cropWidthTablet INT DEFAULT NULL, ADD cropHeightTablet INT DEFAULT NULL, ADD cropWidthMobile INT DEFAULT NULL, ADD cropHeightMobile INT DEFAULT NULL');
        $this->addSql('ALTER TABLE upa_module_gallery_category_media_relations ADD cropWidthDesktop INT DEFAULT NULL, ADD cropHeightDesktop INT DEFAULT NULL, ADD cropWidthLaptop INT DEFAULT NULL, ADD cropHeightLaptop INT DEFAULT NULL, ADD cropWidthTablet INT DEFAULT NULL, ADD cropHeightTablet INT DEFAULT NULL, ADD cropWidthMobile INT DEFAULT NULL, ADD cropHeightMobile INT DEFAULT NULL');
        $this->addSql('ALTER TABLE upa_module_gallery_media_relations ADD cropWidthDesktop INT DEFAULT NULL, ADD cropHeightDesktop INT DEFAULT NULL, ADD cropWidthLaptop INT DEFAULT NULL, ADD cropHeightLaptop INT DEFAULT NULL, ADD cropWidthTablet INT DEFAULT NULL, ADD cropHeightTablet INT DEFAULT NULL, ADD cropWidthMobile INT DEFAULT NULL, ADD cropHeightMobile INT DEFAULT NULL');
        $this->addSql('ALTER TABLE upa_module_map_point_geo_json ADD cropWidthDesktop INT DEFAULT NULL, ADD cropHeightDesktop INT DEFAULT NULL, ADD cropWidthLaptop INT DEFAULT NULL, ADD cropHeightLaptop INT DEFAULT NULL, ADD cropWidthTablet INT DEFAULT NULL, ADD cropHeightTablet INT DEFAULT NULL, ADD cropWidthMobile INT DEFAULT NULL, ADD cropHeightMobile INT DEFAULT NULL');
        $this->addSql('ALTER TABLE upa_module_map_point_media_relations ADD cropWidthDesktop INT DEFAULT NULL, ADD cropHeightDesktop INT DEFAULT NULL, ADD cropWidthLaptop INT DEFAULT NULL, ADD cropHeightLaptop INT DEFAULT NULL, ADD cropWidthTablet INT DEFAULT NULL, ADD cropHeightTablet INT DEFAULT NULL, ADD cropWidthMobile INT DEFAULT NULL, ADD cropHeightMobile INT DEFAULT NULL');
        $this->addSql('ALTER TABLE upa_module_menu_link_media_relation ADD cropWidthDesktop INT DEFAULT NULL, ADD cropHeightDesktop INT DEFAULT NULL, ADD cropWidthLaptop INT DEFAULT NULL, ADD cropHeightLaptop INT DEFAULT NULL, ADD cropWidthTablet INT DEFAULT NULL, ADD cropHeightTablet INT DEFAULT NULL, ADD cropWidthMobile INT DEFAULT NULL, ADD cropHeightMobile INT DEFAULT NULL');
        $this->addSql('ALTER TABLE upa_module_newscast_category_media_relations ADD cropWidthDesktop INT DEFAULT NULL, ADD cropHeightDesktop INT DEFAULT NULL, ADD cropWidthLaptop INT DEFAULT NULL, ADD cropHeightLaptop INT DEFAULT NULL, ADD cropWidthTablet INT DEFAULT NULL, ADD cropHeightTablet INT DEFAULT NULL, ADD cropWidthMobile INT DEFAULT NULL, ADD cropHeightMobile INT DEFAULT NULL');
        $this->addSql('ALTER TABLE upa_module_newscast_media_relations ADD cropWidthDesktop INT DEFAULT NULL, ADD cropHeightDesktop INT DEFAULT NULL, ADD cropWidthLaptop INT DEFAULT NULL, ADD cropHeightLaptop INT DEFAULT NULL, ADD cropWidthTablet INT DEFAULT NULL, ADD cropHeightTablet INT DEFAULT NULL, ADD cropWidthMobile INT DEFAULT NULL, ADD cropHeightMobile INT DEFAULT NULL');
        $this->addSql('ALTER TABLE upa_module_portfolio_card_media_relations ADD cropWidthDesktop INT DEFAULT NULL, ADD cropHeightDesktop INT DEFAULT NULL, ADD cropWidthLaptop INT DEFAULT NULL, ADD cropHeightLaptop INT DEFAULT NULL, ADD cropWidthTablet INT DEFAULT NULL, ADD cropHeightTablet INT DEFAULT NULL, ADD cropWidthMobile INT DEFAULT NULL, ADD cropHeightMobile INT DEFAULT NULL');
        $this->addSql('ALTER TABLE upa_module_portfolio_category_media_relations ADD cropWidthDesktop INT DEFAULT NULL, ADD cropHeightDesktop INT DEFAULT NULL, ADD cropWidthLaptop INT DEFAULT NULL, ADD cropHeightLaptop INT DEFAULT NULL, ADD cropWidthTablet INT DEFAULT NULL, ADD cropHeightTablet INT DEFAULT NULL, ADD cropWidthMobile INT DEFAULT NULL, ADD cropHeightMobile INT DEFAULT NULL');
        $this->addSql('ALTER TABLE upa_module_slider_media_relations ADD cropWidthDesktop INT DEFAULT NULL, ADD cropHeightDesktop INT DEFAULT NULL, ADD cropWidthLaptop INT DEFAULT NULL, ADD cropHeightLaptop INT DEFAULT NULL, ADD cropWidthTablet INT DEFAULT NULL, ADD cropHeightTablet INT DEFAULT NULL, ADD cropWidthMobile INT DEFAULT NULL, ADD cropHeightMobile INT DEFAULT NULL');
        $this->addSql('ALTER TABLE upa_module_tab_content_media_relations ADD cropWidthDesktop INT DEFAULT NULL, ADD cropHeightDesktop INT DEFAULT NULL, ADD cropWidthLaptop INT DEFAULT NULL, ADD cropHeightLaptop INT DEFAULT NULL, ADD cropWidthTablet INT DEFAULT NULL, ADD cropHeightTablet INT DEFAULT NULL, ADD cropWidthMobile INT DEFAULT NULL, ADD cropHeightMobile INT DEFAULT NULL');
        $this->addSql('ALTER TABLE upa_module_timeline_step_media_relations ADD cropWidthDesktop INT DEFAULT NULL, ADD cropHeightDesktop INT DEFAULT NULL, ADD cropWidthLaptop INT DEFAULT NULL, ADD cropHeightLaptop INT DEFAULT NULL, ADD cropWidthTablet INT DEFAULT NULL, ADD cropHeightTablet INT DEFAULT NULL, ADD cropWidthMobile INT DEFAULT NULL, ADD cropHeightMobile INT DEFAULT NULL');
        $this->addSql('UPDATE upa_core_configuration_media_relations SET cropWidthDesktop=maxWidth, cropHeightDesktop=maxHeight, cropWidthTablet=tabletMaxWidth, cropHeightTablet=tabletMaxHeight, cropWidthMobile=mobileMaxWidth, cropHeightMobile=mobileMaxHeight');
        $this->addSql('UPDATE upa_gdpr_group_media_relations SET cropWidthDesktop=maxWidth, cropHeightDesktop=maxHeight, cropWidthTablet=tabletMaxWidth, cropHeightTablet=tabletMaxHeight, cropWidthMobile=mobileMaxWidth, cropHeightMobile=mobileMaxHeight');
        $this->addSql('UPDATE upa_layout_block_media_relations SET cropWidthDesktop=maxWidth, cropHeightDesktop=maxHeight, cropWidthTablet=tabletMaxWidth, cropHeightTablet=tabletMaxHeight, cropWidthMobile=mobileMaxWidth, cropHeightMobile=mobileMaxHeight');
        $this->addSql('UPDATE upa_layout_page_media_relations SET cropWidthDesktop=maxWidth, cropHeightDesktop=maxHeight, cropWidthTablet=tabletMaxWidth, cropHeightTablet=tabletMaxHeight, cropWidthMobile=mobileMaxWidth, cropHeightMobile=mobileMaxHeight');
        $this->addSql('UPDATE upa_layout_zone_media_relations SET cropWidthDesktop=maxWidth, cropHeightDesktop=maxHeight, cropWidthTablet=tabletMaxWidth, cropHeightTablet=tabletMaxHeight, cropWidthMobile=mobileMaxWidth, cropHeightMobile=mobileMaxHeight');
        $this->addSql('UPDATE upa_media_relation SET cropWidthDesktop=maxWidth, cropHeightDesktop=maxHeight, cropWidthTablet=tabletMaxWidth, cropHeightTablet=tabletMaxHeight, cropWidthMobile=mobileMaxWidth, cropHeightMobile=mobileMaxHeight');
        $this->addSql('UPDATE upa_module_agenda_media_relations SET cropWidthDesktop=maxWidth, cropHeightDesktop=maxHeight, cropWidthTablet=tabletMaxWidth, cropHeightTablet=tabletMaxHeight, cropWidthMobile=mobileMaxWidth, cropHeightMobile=mobileMaxHeight');
        $this->addSql('UPDATE upa_module_catalog_category_media_relations SET cropWidthDesktop=maxWidth, cropHeightDesktop=maxHeight, cropWidthTablet=tabletMaxWidth, cropHeightTablet=tabletMaxHeight, cropWidthMobile=mobileMaxWidth, cropHeightMobile=mobileMaxHeight');
        $this->addSql('UPDATE upa_module_catalog_feature_media_relations SET cropWidthDesktop=maxWidth, cropHeightDesktop=maxHeight, cropWidthTablet=tabletMaxWidth, cropHeightTablet=tabletMaxHeight, cropWidthMobile=mobileMaxWidth, cropHeightMobile=mobileMaxHeight');
        $this->addSql('UPDATE upa_module_catalog_feature_value_media_relations SET cropWidthDesktop=maxWidth, cropHeightDesktop=maxHeight, cropWidthTablet=tabletMaxWidth, cropHeightTablet=tabletMaxHeight, cropWidthMobile=mobileMaxWidth, cropHeightMobile=mobileMaxHeight');
        $this->addSql('UPDATE upa_module_catalog_media_relations SET cropWidthDesktop=maxWidth, cropHeightDesktop=maxHeight, cropWidthTablet=tabletMaxWidth, cropHeightTablet=tabletMaxHeight, cropWidthMobile=mobileMaxWidth, cropHeightMobile=mobileMaxHeight');
        $this->addSql('UPDATE upa_module_catalog_product_lot_media_relations SET cropWidthDesktop=maxWidth, cropHeightDesktop=maxHeight, cropWidthTablet=tabletMaxWidth, cropHeightTablet=tabletMaxHeight, cropWidthMobile=mobileMaxWidth, cropHeightMobile=mobileMaxHeight');
        $this->addSql('UPDATE upa_module_catalog_product_media_relations SET cropWidthDesktop=maxWidth, cropHeightDesktop=maxHeight, cropWidthTablet=tabletMaxWidth, cropHeightTablet=tabletMaxHeight, cropWidthMobile=mobileMaxWidth, cropHeightMobile=mobileMaxHeight');
        $this->addSql('UPDATE upa_module_catalog_sub_category_media_relations SET cropWidthDesktop=maxWidth, cropHeightDesktop=maxHeight, cropWidthTablet=tabletMaxWidth, cropHeightTablet=tabletMaxHeight, cropWidthMobile=mobileMaxWidth, cropHeightMobile=mobileMaxHeight');
        $this->addSql('UPDATE upa_module_faq_media_relations SET cropWidthDesktop=maxWidth, cropHeightDesktop=maxHeight, cropWidthTablet=tabletMaxWidth, cropHeightTablet=tabletMaxHeight, cropWidthMobile=mobileMaxWidth, cropHeightMobile=mobileMaxHeight');
        $this->addSql('UPDATE upa_module_faq_question_media_relations SET cropWidthDesktop=maxWidth, cropHeightDesktop=maxHeight, cropWidthTablet=tabletMaxWidth, cropHeightTablet=tabletMaxHeight, cropWidthMobile=mobileMaxWidth, cropHeightMobile=mobileMaxHeight');
        $this->addSql('UPDATE upa_module_gallery_category_media_relations SET cropWidthDesktop=maxWidth, cropHeightDesktop=maxHeight, cropWidthTablet=tabletMaxWidth, cropHeightTablet=tabletMaxHeight, cropWidthMobile=mobileMaxWidth, cropHeightMobile=mobileMaxHeight');
        $this->addSql('UPDATE upa_module_gallery_media_relations SET cropWidthDesktop=maxWidth, cropHeightDesktop=maxHeight, cropWidthTablet=tabletMaxWidth, cropHeightTablet=tabletMaxHeight, cropWidthMobile=mobileMaxWidth, cropHeightMobile=mobileMaxHeight');
        $this->addSql('UPDATE upa_module_map_point_geo_json SET cropWidthDesktop=maxWidth, cropHeightDesktop=maxHeight, cropWidthTablet=tabletMaxWidth, cropHeightTablet=tabletMaxHeight, cropWidthMobile=mobileMaxWidth, cropHeightMobile=mobileMaxHeight');
        $this->addSql('UPDATE upa_module_map_point_media_relations SET cropWidthDesktop=maxWidth, cropHeightDesktop=maxHeight, cropWidthTablet=tabletMaxWidth, cropHeightTablet=tabletMaxHeight, cropWidthMobile=mobileMaxWidth, cropHeightMobile=mobileMaxHeight');
        $this->addSql('UPDATE upa_module_menu_link_media_relation SET cropWidthDesktop=maxWidth, cropHeightDesktop=maxHeight, cropWidthTablet=tabletMaxWidth, cropHeightTablet=tabletMaxHeight, cropWidthMobile=mobileMaxWidth, cropHeightMobile=mobileMaxHeight');
        $this->addSql('UPDATE upa_module_newscast_category_media_relations SET cropWidthDesktop=maxWidth, cropHeightDesktop=maxHeight, cropWidthTablet=tabletMaxWidth, cropHeightTablet=tabletMaxHeight, cropWidthMobile=mobileMaxWidth, cropHeightMobile=mobileMaxHeight');
        $this->addSql('UPDATE upa_module_newscast_media_relations SET cropWidthDesktop=maxWidth, cropHeightDesktop=maxHeight, cropWidthTablet=tabletMaxWidth, cropHeightTablet=tabletMaxHeight, cropWidthMobile=mobileMaxWidth, cropHeightMobile=mobileMaxHeight');
        $this->addSql('UPDATE upa_module_portfolio_card_media_relations SET cropWidthDesktop=maxWidth, cropHeightDesktop=maxHeight, cropWidthTablet=tabletMaxWidth, cropHeightTablet=tabletMaxHeight, cropWidthMobile=mobileMaxWidth, cropHeightMobile=mobileMaxHeight');
        $this->addSql('UPDATE upa_module_portfolio_category_media_relations SET cropWidthDesktop=maxWidth, cropHeightDesktop=maxHeight, cropWidthTablet=tabletMaxWidth, cropHeightTablet=tabletMaxHeight, cropWidthMobile=mobileMaxWidth, cropHeightMobile=mobileMaxHeight');
        $this->addSql('UPDATE upa_module_slider_media_relations SET cropWidthDesktop=maxWidth, cropHeightDesktop=maxHeight, cropWidthTablet=tabletMaxWidth, cropHeightTablet=tabletMaxHeight, cropWidthMobile=mobileMaxWidth, cropHeightMobile=mobileMaxHeight');
        $this->addSql('UPDATE upa_module_tab_content_media_relations SET cropWidthDesktop=maxWidth, cropHeightDesktop=maxHeight, cropWidthTablet=tabletMaxWidth, cropHeightTablet=tabletMaxHeight, cropWidthMobile=mobileMaxWidth, cropHeightMobile=mobileMaxHeight');
        $this->addSql('UPDATE upa_module_timeline_step_media_relations SET cropWidthDesktop=maxWidth, cropHeightDesktop=maxHeight, cropWidthTablet=tabletMaxWidth, cropHeightTablet=tabletMaxHeight, cropWidthMobile=mobileMaxWidth, cropHeightMobile=mobileMaxHeight');
        $this->addSql('ALTER TABLE upa_core_configuration_media_relations DROP maxWidth, DROP maxHeight, DROP tabletMaxWidth, DROP tabletMaxHeight, DROP mobileMaxWidth, DROP mobileMaxHeight');
        $this->addSql('ALTER TABLE upa_gdpr_group_media_relations DROP maxWidth, DROP maxHeight, DROP tabletMaxWidth, DROP tabletMaxHeight, DROP mobileMaxWidth, DROP mobileMaxHeight');
        $this->addSql('ALTER TABLE upa_layout_block_media_relations DROP maxWidth, DROP maxHeight, DROP tabletMaxWidth, DROP tabletMaxHeight, DROP mobileMaxWidth, DROP mobileMaxHeight');
        $this->addSql('ALTER TABLE upa_layout_page_media_relations DROP maxWidth, DROP maxHeight, DROP tabletMaxWidth, DROP tabletMaxHeight, DROP mobileMaxWidth, DROP mobileMaxHeight');
        $this->addSql('ALTER TABLE upa_layout_zone_media_relations DROP maxWidth, DROP maxHeight, DROP tabletMaxWidth, DROP tabletMaxHeight, DROP mobileMaxWidth, DROP mobileMaxHeight');
        $this->addSql('ALTER TABLE upa_media_relation DROP maxWidth, DROP maxHeight, DROP tabletMaxWidth, DROP tabletMaxHeight, DROP mobileMaxWidth, DROP mobileMaxHeight');
        $this->addSql('ALTER TABLE upa_module_agenda_media_relations DROP maxWidth, DROP maxHeight, DROP tabletMaxWidth, DROP tabletMaxHeight, DROP mobileMaxWidth, DROP mobileMaxHeight');
        $this->addSql('ALTER TABLE upa_module_catalog_category_media_relations DROP maxWidth, DROP maxHeight, DROP tabletMaxWidth, DROP tabletMaxHeight, DROP mobileMaxWidth, DROP mobileMaxHeight');
        $this->addSql('ALTER TABLE upa_module_catalog_feature_media_relations DROP maxWidth, DROP maxHeight, DROP tabletMaxWidth, DROP tabletMaxHeight, DROP mobileMaxWidth, DROP mobileMaxHeight');
        $this->addSql('ALTER TABLE upa_module_catalog_feature_value_media_relations DROP maxWidth, DROP maxHeight, DROP tabletMaxWidth, DROP tabletMaxHeight, DROP mobileMaxWidth, DROP mobileMaxHeight');
        $this->addSql('ALTER TABLE upa_module_catalog_media_relations DROP maxWidth, DROP maxHeight, DROP tabletMaxWidth, DROP tabletMaxHeight, DROP mobileMaxWidth, DROP mobileMaxHeight');
        $this->addSql('ALTER TABLE upa_module_catalog_product_lot_media_relations DROP maxWidth, DROP maxHeight, DROP tabletMaxWidth, DROP tabletMaxHeight, DROP mobileMaxWidth, DROP mobileMaxHeight');
        $this->addSql('ALTER TABLE upa_module_catalog_product_media_relations DROP maxWidth, DROP maxHeight, DROP tabletMaxWidth, DROP tabletMaxHeight, DROP mobileMaxWidth, DROP mobileMaxHeight');
        $this->addSql('ALTER TABLE upa_module_catalog_sub_category_media_relations DROP maxWidth, DROP maxHeight, DROP tabletMaxWidth, DROP tabletMaxHeight, DROP mobileMaxWidth, DROP mobileMaxHeight');
        $this->addSql('ALTER TABLE upa_module_faq_media_relations DROP maxWidth, DROP maxHeight, DROP tabletMaxWidth, DROP tabletMaxHeight, DROP mobileMaxWidth, DROP mobileMaxHeight');
        $this->addSql('ALTER TABLE upa_module_faq_question_media_relations DROP maxWidth, DROP maxHeight, DROP tabletMaxWidth, DROP tabletMaxHeight, DROP mobileMaxWidth, DROP mobileMaxHeight');
        $this->addSql('ALTER TABLE upa_module_gallery_category_media_relations DROP maxWidth, DROP maxHeight, DROP tabletMaxWidth, DROP tabletMaxHeight, DROP mobileMaxWidth, DROP mobileMaxHeight');
        $this->addSql('ALTER TABLE upa_module_gallery_media_relations DROP maxWidth, DROP maxHeight, DROP tabletMaxWidth, DROP tabletMaxHeight, DROP mobileMaxWidth, DROP mobileMaxHeight');
        $this->addSql('ALTER TABLE upa_module_map_point_geo_json DROP maxWidth, DROP maxHeight, DROP tabletMaxWidth, DROP tabletMaxHeight, DROP mobileMaxWidth, DROP mobileMaxHeight');
        $this->addSql('ALTER TABLE upa_module_map_point_media_relations DROP maxWidth, DROP maxHeight, DROP tabletMaxWidth, DROP tabletMaxHeight, DROP mobileMaxWidth, DROP mobileMaxHeight');
        $this->addSql('ALTER TABLE upa_module_menu_link_media_relation DROP maxWidth, DROP maxHeight, DROP tabletMaxWidth, DROP tabletMaxHeight, DROP mobileMaxWidth, DROP mobileMaxHeight');
        $this->addSql('ALTER TABLE upa_module_newscast_category_media_relations DROP maxWidth, DROP maxHeight, DROP tabletMaxWidth, DROP tabletMaxHeight, DROP mobileMaxWidth, DROP mobileMaxHeight');
        $this->addSql('ALTER TABLE upa_module_newscast_media_relations DROP maxWidth, DROP maxHeight, DROP tabletMaxWidth, DROP tabletMaxHeight, DROP mobileMaxWidth, DROP mobileMaxHeight');
        $this->addSql('ALTER TABLE upa_module_portfolio_card_media_relations DROP maxWidth, DROP maxHeight, DROP tabletMaxWidth, DROP tabletMaxHeight, DROP mobileMaxWidth, DROP mobileMaxHeight');
        $this->addSql('ALTER TABLE upa_module_portfolio_category_media_relations DROP maxWidth, DROP maxHeight, DROP tabletMaxWidth, DROP tabletMaxHeight, DROP mobileMaxWidth, DROP mobileMaxHeight');
        $this->addSql('ALTER TABLE upa_module_slider_media_relations DROP maxWidth, DROP maxHeight, DROP tabletMaxWidth, DROP tabletMaxHeight, DROP mobileMaxWidth, DROP mobileMaxHeight');
        $this->addSql('ALTER TABLE upa_module_tab_content_media_relations DROP maxWidth, DROP maxHeight, DROP tabletMaxWidth, DROP tabletMaxHeight, DROP mobileMaxWidth, DROP mobileMaxHeight');
        $this->addSql('ALTER TABLE upa_module_timeline_step_media_relations DROP maxWidth, DROP maxHeight, DROP tabletMaxWidth, DROP tabletMaxHeight, DROP mobileMaxWidth, DROP mobileMaxHeight');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE upa_core_configuration_media_relations ADD maxWidth INT DEFAULT NULL, ADD maxHeight INT DEFAULT NULL, ADD tabletMaxWidth INT DEFAULT NULL, ADD tabletMaxHeight INT DEFAULT NULL, ADD mobileMaxWidth INT DEFAULT NULL, ADD mobileMaxHeight INT DEFAULT NULL');
        $this->addSql('ALTER TABLE upa_gdpr_group_media_relations ADD maxWidth INT DEFAULT NULL, ADD maxHeight INT DEFAULT NULL, ADD tabletMaxWidth INT DEFAULT NULL, ADD tabletMaxHeight INT DEFAULT NULL, ADD mobileMaxWidth INT DEFAULT NULL, ADD mobileMaxHeight INT DEFAULT NULL');
        $this->addSql('ALTER TABLE upa_layout_block_media_relations ADD maxWidth INT DEFAULT NULL, ADD maxHeight INT DEFAULT NULL, ADD tabletMaxWidth INT DEFAULT NULL, ADD tabletMaxHeight INT DEFAULT NULL, ADD mobileMaxWidth INT DEFAULT NULL, ADD mobileMaxHeight INT DEFAULT NULL');
        $this->addSql('ALTER TABLE upa_layout_page_media_relations ADD maxWidth INT DEFAULT NULL, ADD maxHeight INT DEFAULT NULL, ADD tabletMaxWidth INT DEFAULT NULL, ADD tabletMaxHeight INT DEFAULT NULL, ADD mobileMaxWidth INT DEFAULT NULL, ADD mobileMaxHeight INT DEFAULT NULL');
        $this->addSql('ALTER TABLE upa_layout_zone_media_relations ADD maxWidth INT DEFAULT NULL, ADD maxHeight INT DEFAULT NULL, ADD tabletMaxWidth INT DEFAULT NULL, ADD tabletMaxHeight INT DEFAULT NULL, ADD mobileMaxWidth INT DEFAULT NULL, ADD mobileMaxHeight INT DEFAULT NULL');
        $this->addSql('ALTER TABLE upa_media_relation ADD maxWidth INT DEFAULT NULL, ADD maxHeight INT DEFAULT NULL, ADD tabletMaxWidth INT DEFAULT NULL, ADD tabletMaxHeight INT DEFAULT NULL, ADD mobileMaxWidth INT DEFAULT NULL, ADD mobileMaxHeight INT DEFAULT NULL');
        $this->addSql('ALTER TABLE upa_module_agenda_media_relations ADD maxWidth INT DEFAULT NULL, ADD maxHeight INT DEFAULT NULL, ADD tabletMaxWidth INT DEFAULT NULL, ADD tabletMaxHeight INT DEFAULT NULL, ADD mobileMaxWidth INT DEFAULT NULL, ADD mobileMaxHeight INT DEFAULT NULL');
        $this->addSql('ALTER TABLE upa_module_catalog_category_media_relations ADD maxWidth INT DEFAULT NULL, ADD maxHeight INT DEFAULT NULL, ADD tabletMaxWidth INT DEFAULT NULL, ADD tabletMaxHeight INT DEFAULT NULL, ADD mobileMaxWidth INT DEFAULT NULL, ADD mobileMaxHeight INT DEFAULT NULL');
        $this->addSql('ALTER TABLE upa_module_catalog_feature_media_relations ADD maxWidth INT DEFAULT NULL, ADD maxHeight INT DEFAULT NULL, ADD tabletMaxWidth INT DEFAULT NULL, ADD tabletMaxHeight INT DEFAULT NULL, ADD mobileMaxWidth INT DEFAULT NULL, ADD mobileMaxHeight INT DEFAULT NULL');
        $this->addSql('ALTER TABLE upa_module_catalog_feature_value_media_relations ADD maxWidth INT DEFAULT NULL, ADD maxHeight INT DEFAULT NULL, ADD tabletMaxWidth INT DEFAULT NULL, ADD tabletMaxHeight INT DEFAULT NULL, ADD mobileMaxWidth INT DEFAULT NULL, ADD mobileMaxHeight INT DEFAULT NULL');
        $this->addSql('ALTER TABLE upa_module_catalog_media_relations ADD maxWidth INT DEFAULT NULL, ADD maxHeight INT DEFAULT NULL, ADD tabletMaxWidth INT DEFAULT NULL, ADD tabletMaxHeight INT DEFAULT NULL, ADD mobileMaxWidth INT DEFAULT NULL, ADD mobileMaxHeight INT DEFAULT NULL');
        $this->addSql('ALTER TABLE upa_module_catalog_product_lot_media_relations ADD maxWidth INT DEFAULT NULL, ADD maxHeight INT DEFAULT NULL, ADD tabletMaxWidth INT DEFAULT NULL, ADD tabletMaxHeight INT DEFAULT NULL, ADD mobileMaxWidth INT DEFAULT NULL, ADD mobileMaxHeight INT DEFAULT NULL');
        $this->addSql('ALTER TABLE upa_module_catalog_product_media_relations ADD maxWidth INT DEFAULT NULL, ADD maxHeight INT DEFAULT NULL, ADD tabletMaxWidth INT DEFAULT NULL, ADD tabletMaxHeight INT DEFAULT NULL, ADD mobileMaxWidth INT DEFAULT NULL, ADD mobileMaxHeight INT DEFAULT NULL');
        $this->addSql('ALTER TABLE upa_module_catalog_sub_category_media_relations ADD maxWidth INT DEFAULT NULL, ADD maxHeight INT DEFAULT NULL, ADD tabletMaxWidth INT DEFAULT NULL, ADD tabletMaxHeight INT DEFAULT NULL, ADD mobileMaxWidth INT DEFAULT NULL, ADD mobileMaxHeight INT DEFAULT NULL');
        $this->addSql('ALTER TABLE upa_module_faq_media_relations ADD maxWidth INT DEFAULT NULL, ADD maxHeight INT DEFAULT NULL, ADD tabletMaxWidth INT DEFAULT NULL, ADD tabletMaxHeight INT DEFAULT NULL, ADD mobileMaxWidth INT DEFAULT NULL, ADD mobileMaxHeight INT DEFAULT NULL');
        $this->addSql('ALTER TABLE upa_module_faq_question_media_relations ADD maxWidth INT DEFAULT NULL, ADD maxHeight INT DEFAULT NULL, ADD tabletMaxWidth INT DEFAULT NULL, ADD tabletMaxHeight INT DEFAULT NULL, ADD mobileMaxWidth INT DEFAULT NULL, ADD mobileMaxHeight INT DEFAULT NULL');
        $this->addSql('ALTER TABLE upa_module_gallery_category_media_relations ADD maxWidth INT DEFAULT NULL, ADD maxHeight INT DEFAULT NULL, ADD tabletMaxWidth INT DEFAULT NULL, ADD tabletMaxHeight INT DEFAULT NULL, ADD mobileMaxWidth INT DEFAULT NULL, ADD mobileMaxHeight INT DEFAULT NULL');
        $this->addSql('ALTER TABLE upa_module_gallery_media_relations ADD maxWidth INT DEFAULT NULL, ADD maxHeight INT DEFAULT NULL, ADD tabletMaxWidth INT DEFAULT NULL, ADD tabletMaxHeight INT DEFAULT NULL, ADD mobileMaxWidth INT DEFAULT NULL, ADD mobileMaxHeight INT DEFAULT NULL');
        $this->addSql('ALTER TABLE upa_module_map_point_geo_json ADD maxWidth INT DEFAULT NULL, ADD maxHeight INT DEFAULT NULL, ADD tabletMaxWidth INT DEFAULT NULL, ADD tabletMaxHeight INT DEFAULT NULL, ADD mobileMaxWidth INT DEFAULT NULL, ADD mobileMaxHeight INT DEFAULT NULL');
        $this->addSql('ALTER TABLE upa_module_map_point_media_relations ADD maxWidth INT DEFAULT NULL, ADD maxHeight INT DEFAULT NULL, ADD tabletMaxWidth INT DEFAULT NULL, ADD tabletMaxHeight INT DEFAULT NULL, ADD mobileMaxWidth INT DEFAULT NULL, ADD mobileMaxHeight INT DEFAULT NULL');
        $this->addSql('ALTER TABLE upa_module_menu_link_media_relation ADD maxWidth INT DEFAULT NULL, ADD maxHeight INT DEFAULT NULL, ADD tabletMaxWidth INT DEFAULT NULL, ADD tabletMaxHeight INT DEFAULT NULL, ADD mobileMaxWidth INT DEFAULT NULL, ADD mobileMaxHeight INT DEFAULT NULL');
        $this->addSql('ALTER TABLE upa_module_newscast_category_media_relations ADD maxWidth INT DEFAULT NULL, ADD maxHeight INT DEFAULT NULL, ADD tabletMaxWidth INT DEFAULT NULL, ADD tabletMaxHeight INT DEFAULT NULL, ADD mobileMaxWidth INT DEFAULT NULL, ADD mobileMaxHeight INT DEFAULT NULL');
        $this->addSql('ALTER TABLE upa_module_newscast_media_relations ADD maxWidth INT DEFAULT NULL, ADD maxHeight INT DEFAULT NULL, ADD tabletMaxWidth INT DEFAULT NULL, ADD tabletMaxHeight INT DEFAULT NULL, ADD mobileMaxWidth INT DEFAULT NULL, ADD mobileMaxHeight INT DEFAULT NULL');
        $this->addSql('ALTER TABLE upa_module_portfolio_card_media_relations ADD maxWidth INT DEFAULT NULL, ADD maxHeight INT DEFAULT NULL, ADD tabletMaxWidth INT DEFAULT NULL, ADD tabletMaxHeight INT DEFAULT NULL, ADD mobileMaxWidth INT DEFAULT NULL, ADD mobileMaxHeight INT DEFAULT NULL');
        $this->addSql('ALTER TABLE upa_module_portfolio_category_media_relations ADD maxWidth INT DEFAULT NULL, ADD maxHeight INT DEFAULT NULL, ADD tabletMaxWidth INT DEFAULT NULL, ADD tabletMaxHeight INT DEFAULT NULL, ADD mobileMaxWidth INT DEFAULT NULL, ADD mobileMaxHeight INT DEFAULT NULL');
        $this->addSql('ALTER TABLE upa_module_slider_media_relations ADD maxWidth INT DEFAULT NULL, ADD maxHeight INT DEFAULT NULL, ADD tabletMaxWidth INT DEFAULT NULL, ADD tabletMaxHeight INT DEFAULT NULL, ADD mobileMaxWidth INT DEFAULT NULL, ADD mobileMaxHeight INT DEFAULT NULL');
        $this->addSql('ALTER TABLE upa_module_tab_content_media_relations ADD maxWidth INT DEFAULT NULL, ADD maxHeight INT DEFAULT NULL, ADD tabletMaxWidth INT DEFAULT NULL, ADD tabletMaxHeight INT DEFAULT NULL, ADD mobileMaxWidth INT DEFAULT NULL, ADD mobileMaxHeight INT DEFAULT NULL');
        $this->addSql('ALTER TABLE upa_module_timeline_step_media_relations ADD maxWidth INT DEFAULT NULL, ADD maxHeight INT DEFAULT NULL, ADD tabletMaxWidth INT DEFAULT NULL, ADD tabletMaxHeight INT DEFAULT NULL, ADD mobileMaxWidth INT DEFAULT NULL, ADD mobileMaxHeight INT DEFAULT NULL');
        $this->addSql('UPDATE upa_core_configuration_media_relations SET maxWidth=cropWidthDesktop, maxHeight=cropHeightDesktop, tabletMaxWidth=cropWidthTablet, tabletMaxHeight=cropHeightTablet, mobileMaxWidth=cropWidthMobile, mobileMaxHeight=cropHeightMobile');
        $this->addSql('UPDATE upa_gdpr_group_media_relations SET maxWidth=cropWidthDesktop, maxHeight=cropHeightDesktop, tabletMaxWidth=cropWidthTablet, tabletMaxHeight=cropHeightTablet, mobileMaxWidth=cropWidthMobile, mobileMaxHeight=cropHeightMobile');
        $this->addSql('UPDATE upa_layout_block_media_relations SET maxWidth=cropWidthDesktop, maxHeight=cropHeightDesktop, tabletMaxWidth=cropWidthTablet, tabletMaxHeight=cropHeightTablet, mobileMaxWidth=cropWidthMobile, mobileMaxHeight=cropHeightMobile');
        $this->addSql('UPDATE upa_layout_page_media_relations SET maxWidth=cropWidthDesktop, maxHeight=cropHeightDesktop, tabletMaxWidth=cropWidthTablet, tabletMaxHeight=cropHeightTablet, mobileMaxWidth=cropWidthMobile, mobileMaxHeight=cropHeightMobile');
        $this->addSql('UPDATE upa_layout_zone_media_relations SET maxWidth=cropWidthDesktop, maxHeight=cropHeightDesktop, tabletMaxWidth=cropWidthTablet, tabletMaxHeight=cropHeightTablet, mobileMaxWidth=cropWidthMobile, mobileMaxHeight=cropHeightMobile');
        $this->addSql('UPDATE upa_media_relation SET maxWidth=cropWidthDesktop, maxHeight=cropHeightDesktop, tabletMaxWidth=cropWidthTablet, tabletMaxHeight=cropHeightTablet, mobileMaxWidth=cropWidthMobile, mobileMaxHeight=cropHeightMobile');
        $this->addSql('UPDATE upa_module_agenda_media_relations SET maxWidth=cropWidthDesktop, maxHeight=cropHeightDesktop, tabletMaxWidth=cropWidthTablet, tabletMaxHeight=cropHeightTablet, mobileMaxWidth=cropWidthMobile, mobileMaxHeight=cropHeightMobile');
        $this->addSql('UPDATE upa_module_catalog_category_media_relations SET maxWidth=cropWidthDesktop, maxHeight=cropHeightDesktop, tabletMaxWidth=cropWidthTablet, tabletMaxHeight=cropHeightTablet, mobileMaxWidth=cropWidthMobile, mobileMaxHeight=cropHeightMobile');
        $this->addSql('UPDATE upa_module_catalog_feature_media_relations SET maxWidth=cropWidthDesktop, maxHeight=cropHeightDesktop, tabletMaxWidth=cropWidthTablet, tabletMaxHeight=cropHeightTablet, mobileMaxWidth=cropWidthMobile, mobileMaxHeight=cropHeightMobile');
        $this->addSql('UPDATE upa_module_catalog_feature_value_media_relations SET maxWidth=cropWidthDesktop, maxHeight=cropHeightDesktop, tabletMaxWidth=cropWidthTablet, tabletMaxHeight=cropHeightTablet, mobileMaxWidth=cropWidthMobile, mobileMaxHeight=cropHeightMobile');
        $this->addSql('UPDATE upa_module_catalog_media_relations SET maxWidth=cropWidthDesktop, maxHeight=cropHeightDesktop, tabletMaxWidth=cropWidthTablet, tabletMaxHeight=cropHeightTablet, mobileMaxWidth=cropWidthMobile, mobileMaxHeight=cropHeightMobile');
        $this->addSql('UPDATE upa_module_catalog_product_lot_media_relations SET maxWidth=cropWidthDesktop, maxHeight=cropHeightDesktop, tabletMaxWidth=cropWidthTablet, tabletMaxHeight=cropHeightTablet, mobileMaxWidth=cropWidthMobile, mobileMaxHeight=cropHeightMobile');
        $this->addSql('UPDATE upa_module_catalog_product_media_relations SET maxWidth=cropWidthDesktop, maxHeight=cropHeightDesktop, tabletMaxWidth=cropWidthTablet, tabletMaxHeight=cropHeightTablet, mobileMaxWidth=cropWidthMobile, mobileMaxHeight=cropHeightMobile');
        $this->addSql('UPDATE upa_module_catalog_sub_category_media_relations SET maxWidth=cropWidthDesktop, maxHeight=cropHeightDesktop, tabletMaxWidth=cropWidthTablet, tabletMaxHeight=cropHeightTablet, mobileMaxWidth=cropWidthMobile, mobileMaxHeight=cropHeightMobile');
        $this->addSql('UPDATE upa_module_faq_media_relations SET maxWidth=cropWidthDesktop, maxHeight=cropHeightDesktop, tabletMaxWidth=cropWidthTablet, tabletMaxHeight=cropHeightTablet, mobileMaxWidth=cropWidthMobile, mobileMaxHeight=cropHeightMobile');
        $this->addSql('UPDATE upa_module_faq_question_media_relations SET maxWidth=cropWidthDesktop, maxHeight=cropHeightDesktop, tabletMaxWidth=cropWidthTablet, tabletMaxHeight=cropHeightTablet, mobileMaxWidth=cropWidthMobile, mobileMaxHeight=cropHeightMobile');
        $this->addSql('UPDATE upa_module_gallery_category_media_relations SET maxWidth=cropWidthDesktop, maxHeight=cropHeightDesktop, tabletMaxWidth=cropWidthTablet, tabletMaxHeight=cropHeightTablet, mobileMaxWidth=cropWidthMobile, mobileMaxHeight=cropHeightMobile');
        $this->addSql('UPDATE upa_module_gallery_media_relations SET maxWidth=cropWidthDesktop, maxHeight=cropHeightDesktop, tabletMaxWidth=cropWidthTablet, tabletMaxHeight=cropHeightTablet, mobileMaxWidth=cropWidthMobile, mobileMaxHeight=cropHeightMobile');
        $this->addSql('UPDATE upa_module_map_point_geo_json SET maxWidth=cropWidthDesktop, maxHeight=cropHeightDesktop, tabletMaxWidth=cropWidthTablet, tabletMaxHeight=cropHeightTablet, mobileMaxWidth=cropWidthMobile, mobileMaxHeight=cropHeightMobile');
        $this->addSql('UPDATE upa_module_map_point_media_relations SET maxWidth=cropWidthDesktop, maxHeight=cropHeightDesktop, tabletMaxWidth=cropWidthTablet, tabletMaxHeight=cropHeightTablet, mobileMaxWidth=cropWidthMobile, mobileMaxHeight=cropHeightMobile');
        $this->addSql('UPDATE upa_module_menu_link_media_relation SET maxWidth=cropWidthDesktop, maxHeight=cropHeightDesktop, tabletMaxWidth=cropWidthTablet, tabletMaxHeight=cropHeightTablet, mobileMaxWidth=cropWidthMobile, mobileMaxHeight=cropHeightMobile');
        $this->addSql('UPDATE upa_module_newscast_category_media_relations SET maxWidth=cropWidthDesktop, maxHeight=cropHeightDesktop, tabletMaxWidth=cropWidthTablet, tabletMaxHeight=cropHeightTablet, mobileMaxWidth=cropWidthMobile, mobileMaxHeight=cropHeightMobile');
        $this->addSql('UPDATE upa_module_newscast_media_relations SET maxWidth=cropWidthDesktop, maxHeight=cropHeightDesktop, tabletMaxWidth=cropWidthTablet, tabletMaxHeight=cropHeightTablet, mobileMaxWidth=cropWidthMobile, mobileMaxHeight=cropHeightMobile');
        $this->addSql('UPDATE upa_module_portfolio_card_media_relations SET maxWidth=cropWidthDesktop, maxHeight=cropHeightDesktop, tabletMaxWidth=cropWidthTablet, tabletMaxHeight=cropHeightTablet, mobileMaxWidth=cropWidthMobile, mobileMaxHeight=cropHeightMobile');
        $this->addSql('UPDATE upa_module_portfolio_category_media_relations SET maxWidth=cropWidthDesktop, maxHeight=cropHeightDesktop, tabletMaxWidth=cropWidthTablet, tabletMaxHeight=cropHeightTablet, mobileMaxWidth=cropWidthMobile, mobileMaxHeight=cropHeightMobile');
        $this->addSql('UPDATE upa_module_slider_media_relations SET maxWidth=cropWidthDesktop, maxHeight=cropHeightDesktop, tabletMaxWidth=cropWidthTablet, tabletMaxHeight=cropHeightTablet, mobileMaxWidth=cropWidthMobile, mobileMaxHeight=cropHeightMobile');
        $this->addSql('UPDATE upa_module_tab_content_media_relations SET maxWidth=cropWidthDesktop, maxHeight=cropHeightDesktop, tabletMaxWidth=cropWidthTablet, tabletMaxHeight=cropHeightTablet, mobileMaxWidth=cropWidthMobile, mobileMaxHeight=cropHeightMobile');
        $this->addSql('UPDATE upa_module_timeline_step_media_relations SET maxWidth=cropWidthDesktop, maxHeight=cropHeightDesktop, tabletMaxWidth=cropWidthTablet, tabletMaxHeight=cropHeightTablet, mobileMaxWidth=cropWidthMobile, mobileMaxHeight=cropHeightMobile');
        $this->addSql('ALTER TABLE upa_core_configuration_media_relations DROP cropWidthDesktop, DROP cropHeightDesktop, DROP cropWidthLaptop, DROP cropHeightLaptop, DROP cropWidthTablet, DROP cropHeightTablet, DROP cropWidthMobile, DROP cropHeightMobile');
        $this->addSql('ALTER TABLE upa_gdpr_group_media_relations DROP cropWidthDesktop, DROP cropHeightDesktop, DROP cropWidthLaptop, DROP cropHeightLaptop, DROP cropWidthTablet, DROP cropHeightTablet, DROP cropWidthMobile, DROP cropHeightMobile');
        $this->addSql('ALTER TABLE upa_layout_block_media_relations DROP cropWidthDesktop, DROP cropHeightDesktop, DROP cropWidthLaptop, DROP cropHeightLaptop, DROP cropWidthTablet, DROP cropHeightTablet, DROP cropWidthMobile, DROP cropHeightMobile');
        $this->addSql('ALTER TABLE upa_layout_page_media_relations DROP cropWidthDesktop, DROP cropHeightDesktop, DROP cropWidthLaptop, DROP cropHeightLaptop, DROP cropWidthTablet, DROP cropHeightTablet, DROP cropWidthMobile, DROP cropHeightMobile');
        $this->addSql('ALTER TABLE upa_layout_zone_media_relations DROP cropWidthDesktop, DROP cropHeightDesktop, DROP cropWidthLaptop, DROP cropHeightLaptop, DROP cropWidthTablet, DROP cropHeightTablet, DROP cropWidthMobile, DROP cropHeightMobile');
        $this->addSql('ALTER TABLE upa_media_relation DROP cropWidthDesktop, DROP cropHeightDesktop, DROP cropWidthLaptop, DROP cropHeightLaptop, DROP cropWidthTablet, DROP cropHeightTablet, DROP cropWidthMobile, DROP cropHeightMobile');
        $this->addSql('ALTER TABLE upa_module_agenda_media_relations DROP cropWidthDesktop, DROP cropHeightDesktop, DROP cropWidthLaptop, DROP cropHeightLaptop, DROP cropWidthTablet, DROP cropHeightTablet, DROP cropWidthMobile, DROP cropHeightMobile');
        $this->addSql('ALTER TABLE upa_module_catalog_category_media_relations DROP cropWidthDesktop, DROP cropHeightDesktop, DROP cropWidthLaptop, DROP cropHeightLaptop, DROP cropWidthTablet, DROP cropHeightTablet, DROP cropWidthMobile, DROP cropHeightMobile');
        $this->addSql('ALTER TABLE upa_module_catalog_feature_media_relations DROP cropWidthDesktop, DROP cropHeightDesktop, DROP cropWidthLaptop, DROP cropHeightLaptop, DROP cropWidthTablet, DROP cropHeightTablet, DROP cropWidthMobile, DROP cropHeightMobile');
        $this->addSql('ALTER TABLE upa_module_catalog_feature_value_media_relations DROP cropWidthDesktop, DROP cropHeightDesktop, DROP cropWidthLaptop, DROP cropHeightLaptop, DROP cropWidthTablet, DROP cropHeightTablet, DROP cropWidthMobile, DROP cropHeightMobile');
        $this->addSql('ALTER TABLE upa_module_catalog_media_relations DROP cropWidthDesktop, DROP cropHeightDesktop, DROP cropWidthLaptop, DROP cropHeightLaptop, DROP cropWidthTablet, DROP cropHeightTablet, DROP cropWidthMobile, DROP cropHeightMobile');
        $this->addSql('ALTER TABLE upa_module_catalog_product_lot_media_relations DROP cropWidthDesktop, DROP cropHeightDesktop, DROP cropWidthLaptop, DROP cropHeightLaptop, DROP cropWidthTablet, DROP cropHeightTablet, DROP cropWidthMobile, DROP cropHeightMobile');
        $this->addSql('ALTER TABLE upa_module_catalog_product_media_relations DROP cropWidthDesktop, DROP cropHeightDesktop, DROP cropWidthLaptop, DROP cropHeightLaptop, DROP cropWidthTablet, DROP cropHeightTablet, DROP cropWidthMobile, DROP cropHeightMobile');
        $this->addSql('ALTER TABLE upa_module_catalog_sub_category_media_relations DROP cropWidthDesktop, DROP cropHeightDesktop, DROP cropWidthLaptop, DROP cropHeightLaptop, DROP cropWidthTablet, DROP cropHeightTablet, DROP cropWidthMobile, DROP cropHeightMobile');
        $this->addSql('ALTER TABLE upa_module_faq_media_relations DROP cropWidthDesktop, DROP cropHeightDesktop, DROP cropWidthLaptop, DROP cropHeightLaptop, DROP cropWidthTablet, DROP cropHeightTablet, DROP cropWidthMobile, DROP cropHeightMobile');
        $this->addSql('ALTER TABLE upa_module_faq_question_media_relations DROP cropWidthDesktop, DROP cropHeightDesktop, DROP cropWidthLaptop, DROP cropHeightLaptop, DROP cropWidthTablet, DROP cropHeightTablet, DROP cropWidthMobile, DROP cropHeightMobile');
        $this->addSql('ALTER TABLE upa_module_gallery_category_media_relations DROP cropWidthDesktop, DROP cropHeightDesktop, DROP cropWidthLaptop, DROP cropHeightLaptop, DROP cropWidthTablet, DROP cropHeightTablet, DROP cropWidthMobile, DROP cropHeightMobile');
        $this->addSql('ALTER TABLE upa_module_gallery_media_relations DROP cropWidthDesktop, DROP cropHeightDesktop, DROP cropWidthLaptop, DROP cropHeightLaptop, DROP cropWidthTablet, DROP cropHeightTablet, DROP cropWidthMobile, DROP cropHeightMobile');
        $this->addSql('ALTER TABLE upa_module_map_point_geo_json DROP cropWidthDesktop, DROP cropHeightDesktop, DROP cropWidthLaptop, DROP cropHeightLaptop, DROP cropWidthTablet, DROP cropHeightTablet, DROP cropWidthMobile, DROP cropHeightMobile');
        $this->addSql('ALTER TABLE upa_module_map_point_media_relations DROP cropWidthDesktop, DROP cropHeightDesktop, DROP cropWidthLaptop, DROP cropHeightLaptop, DROP cropWidthTablet, DROP cropHeightTablet, DROP cropWidthMobile, DROP cropHeightMobile');
        $this->addSql('ALTER TABLE upa_module_menu_link_media_relation DROP cropWidthDesktop, DROP cropHeightDesktop, DROP cropWidthLaptop, DROP cropHeightLaptop, DROP cropWidthTablet, DROP cropHeightTablet, DROP cropWidthMobile, DROP cropHeightMobile');
        $this->addSql('ALTER TABLE upa_module_newscast_category_media_relations DROP cropWidthDesktop, DROP cropHeightDesktop, DROP cropWidthLaptop, DROP cropHeightLaptop, DROP cropWidthTablet, DROP cropHeightTablet, DROP cropWidthMobile, DROP cropHeightMobile');
        $this->addSql('ALTER TABLE upa_module_newscast_media_relations DROP cropWidthDesktop, DROP cropHeightDesktop, DROP cropWidthLaptop, DROP cropHeightLaptop, DROP cropWidthTablet, DROP cropHeightTablet, DROP cropWidthMobile, DROP cropHeightMobile');
        $this->addSql('ALTER TABLE upa_module_portfolio_card_media_relations DROP cropWidthDesktop, DROP cropHeightDesktop, DROP cropWidthLaptop, DROP cropHeightLaptop, DROP cropWidthTablet, DROP cropHeightTablet, DROP cropWidthMobile, DROP cropHeightMobile');
        $this->addSql('ALTER TABLE upa_module_portfolio_category_media_relations DROP cropWidthDesktop, DROP cropHeightDesktop, DROP cropWidthLaptop, DROP cropHeightLaptop, DROP cropWidthTablet, DROP cropHeightTablet, DROP cropWidthMobile, DROP cropHeightMobile');
        $this->addSql('ALTER TABLE upa_module_slider_media_relations DROP cropWidthDesktop, DROP cropHeightDesktop, DROP cropWidthLaptop, DROP cropHeightLaptop, DROP cropWidthTablet, DROP cropHeightTablet, DROP cropWidthMobile, DROP cropHeightMobile');
        $this->addSql('ALTER TABLE upa_module_tab_content_media_relations DROP cropWidthDesktop, DROP cropHeightDesktop, DROP cropWidthLaptop, DROP cropHeightLaptop, DROP cropWidthTablet, DROP cropHeightTablet, DROP cropWidthMobile, DROP cropHeightMobile');
        $this->addSql('ALTER TABLE upa_module_timeline_step_media_relations DROP cropWidthDesktop, DROP cropHeightDesktop, DROP cropWidthLaptop, DROP cropHeightLaptop, DROP cropWidthTablet, DROP cropHeightTablet, DROP cropWidthMobile, DROP cropHeightMobile');
    }
}
